name: Build APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Instalar workload maui-android
        run: |
          dotnet workload install maui-android

      - name: Restaurar dependências
        run: dotnet restore

      - name: Gerar APK
        run: |
          dotnet build -f net9.0-android -c Release

      - name: Upload do APK
        uses: actions/upload-artifact@v4
        with:
          name: CalculadoraPLS
          path: |
            **/*-Signed.apk
            **/*.apk
          retention-days: 30
